[package]
name = "ui-src"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = { version = "0.7.8", features = ["csr"] }
leptos_router = "0.7.8"
lingua-i18n-rs = "0.2.0"
serde = { version = "1.0.219", features = ["derive"] }
